#!/usr/bin/env bash

set -eou pipefail

echo "Starting pre-commit hook"

staged_files=$(git diff --name-only --cached)

if [[ $(echo "$staged_files" | grep "^frontend") ]]; then
  echo "Changes in frontend detected"

  cd frontend
  
  npm run lint
  npm run prettier:check

  echo "Frontend checks passing"
  cd - > /dev/null
else
  echo "No changes in frontend, skipping checks"
fi

echo
echo "✅ Pre-commit hooks completed"
echo
