kind: pipeline
type: docker
name: default

.nodejs: &nodejs
  image: node:14-alpine

steps:
  - name: check node modules
    <<: *nodejs
    commands:
      - cd app
      - npm audit --audit-level="high"
      - npm audit --production

  - name: install node modules
    <<: *nodejs
    commands:
      - cd app
      - npm ci

  - name: lint javascript
    <<: *nodejs
    commands:
      - cd app
      - npm run linter
    depends_on:
      - install dependencies

  - name: build
    <<: *nodejs
    commands:
      - cd app
      - npm run build
    depends_on:
      - install dependencies
