kind: pipeline
name: default

.node-image: &node-image
  image: node:10-alpine

.terraform-image: &terraform-image
  image: hashicorp/terraform:light
  entrypoint: [""]

steps:
- name: check-dependencies
  <<: *node-image
  commands:
    - npm audit

- name: install
  <<: *node-image
  commands:
    - npm ci

- name: linter
  <<: *node-image
  commands:
    - npm run linter:js

- name: deploy
  <<: *terraform-image
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_DEFAULT_REGION:
      from_secret: AWS_DEFAULT_REGION
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    STATE_BUCKET:
      from_secret: STATE_BUCKET
    TEST_VAR:
      from_secret: TEST_VAR
    SOME_VAR: "Hello you"
  commands:
    - cd infrastructure
    - export TF_VAR_environment="feature"
    - export TF_VAR_git_branch="$DRONE_BRANCH"
    - export TF_VAR_git_commit="$DRONE_COMMIT_SHA"
    - export TF_VAR_git_repository="$DRONE_COMMIT_LINK"
    - echo "TF_VAR_environment - $TF_VAR_environment"
    - export temp=$TEST_VAR
    - echo "TEST_VAR - $temp"
    - echo "SOME_VAR - $SOME_VAR"
    # - terraform init --backend-config="bucket=$STATE_BUCKET"
