kind: pipeline
type: docker
name: default

steps:
  - name: check node modules
    image: node:14-alpine
    commands:
      - cd app
      - npm audit --audit-level="high"
      - npm audit --production

  - name: install node modules
    image: node:14-alpine
    commands:
      - cd app
      - npm ci

  - name: lint javascript
    image: node:14-alpine
    commands:
      - cd app
      - npm run linter
    depends_on:
      - install dependencies

  - name: build
    image: node:14-alpine
    commands:
      - cd app
      - npm run build
    depends_on:
      - install dependencies
