kind: pipeline
type: docker
name: default

.nodejs: &nodejs
  image: node:14-alpine

.terraform: &terraform
  image: hashicorp/terraform:0.14.9

steps:
  - name: check node modules
    <<: *nodejs
    commands:
      - cd app
      - npm audit --audit-level="high"
      - npm audit --production

  - name: install node modules
    <<: *nodejs
    commands:
      - cd app
      - npm ci

  - name: validate terraform
    <<: *terraform
    commands:
      - cd infrastructure
      - terraform init -backend=false
      - terraform validate

  - name: check terraform formatting
    <<: *terraform
    commands:
      - cd infrastructure
      - terraform fmt -check -recursive

  - name: lint javascript
    <<: *nodejs
    commands:
      - cd app
      - npm run linter
    depends_on:
      - install dependencies

  - name: build
    <<: *nodejs
    commands:
      - cd app
      - npm run build
    depends_on:
      - install dependencies
