kind: pipeline
type: docker
name: default

.nodejs: &nodejs
  image: node:14-alpine

steps:
  - name: check dependencies
    <<: *nodejs
    commands:
      - cd app
      - npm run lax-audit

  - name: install dependencies
    <<: *nodejs
    commands:
      - cd app

  - name: lint javascript
    <<: *nodejs
    commands:
      - cd app
      - npm run linter
    depends_on:
      - install dependencies

  - name: build
    <<: *nodejs
    commands:
      - cd app
      - npm run build
    depends_on:
      - install dependencies
