name: Deploy App
run-name: ${{ github.actor }} is is deploying to production 🚀
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./apps/frontend
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.6
      - name: Use Node.js 20.12.2
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --filter @alastair-smith/frontend
      - name: Build
        run: pnpm run --dir "./apps/frontend" build:cloudflare
      - name: Deploy
        run: pnpm run --dir "./apps/frontend" deploy -- --branch main

  register-deployment:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Register Deployment
        uses: actions/github-script@v6
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'main',
              environment: 'production',
              auto_merge: false,
              transient_environment: false,
              required_contexts: [],
              production_environment: true
            })
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: 'success',
              environment_url: 'https://alsmith.dev'
            })
