name: Deploy App
run-name: ${{ github.actor }} is deploying ${{ github.ref_name }} 🚀
on: [pull_request]
defaults:
  run:
    working-directory: ./frontend
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:18.17.1-alpine3.18
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Build
        run: npm run build:cloudflare
      - name: Deploy
        run: npm run deploy
  
  comment:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Deployed to <https://${{ github.ref_name }}.website-frontend-4fb.pages.dev>.
