name: Deploy App
run-name: ${{ github.actor }} is is deploying to production 🚀
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./apps/frontend
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: docker.io/gplane/pnpm:9.0.6-node20@sha256:117068a65810b9e52babf592bdc1e09c76ad502df7b8942c3fe1d2c95855cd78
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install packages
        run: pnpm install
      - name: Build
        run: pnpm run build:cloudflare
      - name: Deploy
        run: pnpm run deploy -- --branch main

  register-deployment:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Register Deployment
        uses: actions/github-script@v6
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'main',
              environment: 'production',
              auto_merge: false,
              transient_environment: false,
              required_contexts: [],
              production_environment: true
            })
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: 'success',
              environment_url: 'https://alsmith.dev'
            })
