name: Validate Infrastructure
run-name: ${{ github.actor }} is validating infrastructure code on branch ${{ github.ref_name }} 🚀
on: [push]
defaults:
  run:
    working-directory: ./infrastructure
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.5.7
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Initialise Terraform
        run: terraform init -backend=false
      - name: Check formatting
        run: terraform fmt -check -recursive
      - name: Validate
        run: terraform validate

  terraform-lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terraform-linters/tflint-bundle:v0.48.0.0
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: tflint init
        run: tflint --init
      - name: tflint
        run: tflint --recursive

  # terraform-security-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repo
  #       uses: actions/checkout@master
  #     - name: tfsec
  #       uses: aquasecurity/tfsec-action@v1.0.3

  # terraform-compliance:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: eerkunt/terraform-compliance:1.3.44
  #   steps:
  #     - name: Checkout repository code
  #       uses: actions/checkout@v3
  #     - name: Terraform compliance
  #       run:  terraform-compliance -f ./test/compliance
