name: Validate App
run-name: ${{ github.actor }} is validating application code on branch ${{ github.ref_name }} 🚀
on: [push]
jobs:
  audit-node-modules:
    runs-on: ubuntu-latest
    container:
      image: node:18.17.1-alpine3.18
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Change directory
        run: cd frontend
      - name: Install packages
        run: npm audit

  lint-js:
    runs-on: ubuntu-latest
    container:
      image: node:18.17.1-alpine3.18
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Change directory
        run: cd frontend
      - name: Install packages
        run: npm ci
      - name: Lint
        run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    container:
      image: node:18.17.1-alpine3.18
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Change directory
        run: cd frontend
      - name: Install packages
        run: npm ci
      - name: Check Prettier
        run: npm run prettier:check

  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: node:18.17.1-alpine3.18
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Change directory
        run: cd frontend
      - name: Install packages
        run: npm ci
      - name: Check Prettier
        run: npm run test:unit
  
  integration-tests:
    runs-on: ubuntu-latest
    container:
      image: node:18.17.1-alpine3.18
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Change directory
        run: cd frontend
      - name: Install packages
        run: npm ci
      - name: Check Prettier
        run: npm run test:integration

  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: node:18.17.1-alpine3.18
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Change directory
        run: cd frontend
      - name: Install packages
        run: npm ci
      - name: Check Prettier
        run: npm run test:e2e
