name: Validate App
run-name: ${{ github.actor }} is validating application code on branch ${{ github.head_ref }} 🚀
on: [pull_request]
defaults:
  run:
    working-directory: ./apps/frontend
jobs:
  audit-node-modules:
    runs-on: ubuntu-latest
    container:
      image: docker.io/gplane/pnpm:9.0.6-node20@sha256:117068a65810b9e52babf592bdc1e09c76ad502df7b8942c3fe1d2c95855cd78
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Audit packages
        run: pnpm audit || echo allow failure

  lint-js:
    runs-on: ubuntu-latest
    container:
      image: docker.io/gplane/pnpm:9.0.6-node20@sha256:117068a65810b9e52babf592bdc1e09c76ad502df7b8942c3fe1d2c95855cd78
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install packages
        run: pnpm install
      - name: Lint
        run: pnpm lint

  prettier:
    runs-on: ubuntu-latest
    container:
      image: docker.io/gplane/pnpm:9.0.6-node20@sha256:117068a65810b9e52babf592bdc1e09c76ad502df7b8942c3fe1d2c95855cd78
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install packages
        run: pnpm install
      - name: Check Prettier
        run: pnpm run prettier:check

  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: docker.io/gplane/pnpm:9.0.6-node20@sha256:117068a65810b9e52babf592bdc1e09c76ad502df7b8942c3fe1d2c95855cd78
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install packages
        run: pnpm install
      - name: Run unit tests
        run: pnpm run test:unit

  integration-tests:
    runs-on: ubuntu-latest
    container:
      image: docker.io/gplane/pnpm:9.0.6-node20@sha256:117068a65810b9e52babf592bdc1e09c76ad502df7b8942c3fe1d2c95855cd78
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install packages
        run: pnpm install
      - name: Run integration tests
        run: pnpm run test:integration

  deploy-preview:
    runs-on: ubuntu-latest
    needs:
      - audit-node-modules
      - lint-js
      - prettier
      - unit-tests
      - integration-tests
    container:
      image: docker.io/gplane/pnpm:9.0.6-node20@sha256:117068a65810b9e52babf592bdc1e09c76ad502df7b8942c3fe1d2c95855cd78
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install packages
        run: pnpm install
      - name: Build
        run: pnpm run build:cloudflare
      - name: Deploy
        run: pnpm run deploy -- --branch ${{ github.head_ref }}

  register-deployment:
    runs-on: ubuntu-latest
    needs: [deploy-preview]
    steps:
      - name: Register Deployment
        uses: actions/github-script@v6
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `${{ github.head_ref }}`,
              environment: `preview-${{ github.head_ref }}`,
              auto_merge: false,
              transient_environment: true,
              required_contexts: [],
              production_environment: false
            })
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: 'success',
              environment_url: `https://${{ github.head_ref }}.website-frontend-4fb.pages.dev`
            })

  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-preview
    container:
      image: docker.io/gplane/pnpm:9.0.6-node20@sha256:117068a65810b9e52babf592bdc1e09c76ad502df7b8942c3fe1d2c95855cd78
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install packages
        run: pnpm install
      - name: Run E2E tests
        run: pnpm run test:e2e
