name: Validate App
run-name: ${{ github.actor }} is validating application code on branch ${{ github.head_ref }} 🚀
on: [pull_request]

# skip commit hook setup in CI
env:
  HUSKY: 0

jobs:
  audit-node-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.6
      - name: Use Node.js 20.12.2
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
      - name: Audit packages
        run: pnpm audit || echo allow failure

  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.6
      - name: Use Node.js 20.12.2
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install -w
      - name: Check formatting
        run: pnpm run -w formatter

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.6
      - name: Use Node.js 20.12.2
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install --filter @alastair-smith/frontend
      - name: Tests
        run: pnpm run --dir "./apps/frontend" test:ci

  deploy-preview:
    runs-on: ubuntu-latest
    needs:
      - audit-node-modules
      - test
      - formatter
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GIT_BRANCH_NAME: ${{ github.head_ref }}
      ENVIRONMENT: preview
      VERSION: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.6
      - name: Use Node.js 20.12.2
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install --filter @alastair-smith/frontend
      - name: Build
        run: pnpm run --dir "./apps/frontend" build:cloudflare
      - name: Deploy
        run: pnpm run --dir "./apps/frontend" deploy --branch ${{ github.head_ref }}

  register-deployment:
    runs-on: ubuntu-latest
    needs: [deploy-preview]
    steps:
      - name: Register Deployment
        uses: actions/github-script@v6
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `${{ github.head_ref }}`,
              environment: `preview-${{ github.head_ref }}`,
              auto_merge: false,
              transient_environment: true,
              required_contexts: [],
              production_environment: false
            })
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: 'success',
              environment_url: `https://${{ github.head_ref }}.website-frontend-4fb.pages.dev`
            })
